version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - fundamen-network
    command: postgres -c "port=${DATABASE_PORT}"  # Pass the custom port at startup

  nest:
    image: theantekirta/fundamen_nest
    environment:
      BE_PORT: ${BE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_PRIVATE_KEY: ${STRIPE_PRIVATE_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      UPLOAD_FOLDER: '/var/www/static/uploads'
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - uploads:/var/www/static/uploads
    ports:
      - "${BE_PORT}:${BE_PORT}"
    networks:
      - fundamen-network
    command: "npm run start:prod"

  nuxt:
    image: theantekirta/fundamen_nuxt
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${NUXT_HOST_PORT}:${NUXT_DOCKER_PORT}"
    networks:
      - fundamen-network
    command: "npm run prod"

  nginx:
    image: nginx:1-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - uploads:/var/www/static/uploads
    ports:
      - "80:80"
    networks:
      - fundamen-network
    depends_on:
      - nuxt
      - nest

volumes:
  postgres_data:
  uploads:

networks:
  fundamen-network:
    driver: bridge
