version: '3.8'

services:
  nest:
    image: theantekirta/fundamen_nest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:3002"
    command: "npm run start:prod"
  nuxt:
    image: theantekirta/fundamen_nuxt
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: "node .output/server/index.mjs"
