export const NUMBER_OF_CATEGORIES = 20;
export const NUMBER_OF_PARENT_CATEGORIES = 5;
export const NUMBER_OF_PRODUCT_TYPES = 2;
export const NUMBER_OF_PRODUCT_PROPERTIES = 20;
export const NUMBER_OF_PRODUCT_PROPERTIES_VALUES = 60;
export const NUMBER_OF_PRODUCTS = 100;
