name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build the Docker image
        run: docker-compose build

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Tag the Docker nuxt image
        run: docker tag fundamen-nuxt theantekirta/fundamen-nuxt

      - name: Tag the Docker nest image
        run: docker tag fundamen-nest theantekirta/fundamen-nest

      - name: Push the Docker nuxt image
        run: docker push theantekirta/fundamen-nuxt

      - name: Push the Docker nest image
        run: docker push theantekirta/fundamen-nest  
  
 

